import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Homepage from "../components/homepage/index";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Kantumruy+Pro:wght@100&family=Orbitron:wght@400;500;600;700&family=Poiret+One&display=swap" rel="stylesheet" />
      </Head>
      <Homepage />
    </div>
  );
};

export default Home;
